In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("https://github.com/singhrau0/Big-Data-Preprocessing/raw/refs/heads/main/spam.csv")

In [4]:
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
#data cleaning
cleaned_list=[]
for i in df['Message']:
    s=''
    for j in i:
        if j.isalpha() or j==" ":
            s=s+j
    s=s.split()
    cleaned_data=(" ".join(s)).lower()
    cleaned_list.append(cleaned_data)
df['Message']=cleaned_list

In [6]:
df

     Category                                            Message
0         ham  go until jurong point crazy available only in ...
1         ham                            ok lar joking wif u oni
2        spam  free entry in a wkly comp to win fa cup final ...
3         ham        u dun say so early hor u c already then say
4         ham  nah i dont think he goes to usf he lives aroun...
...       ...                                                ...
5567     spam  this is the nd time we have tried contact u u ...
5568      ham                will ü b going to esplanade fr home
5569      ham  pity was in mood for that soany other suggestions
5570      ham  the guy did some bitching but i acted like id ...
5571      ham                          rofl its true to its name

[5572 rows x 2 columns]

In [7]:
import re
#regular expression
!pip install nltk
import nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in /opt/conda/lib/python3.11/site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from nltk) (1.4.2)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.6.28-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from nltk) (4.66.5)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 96.8 MB/s eta 0:00:00
Downloading regex-2026.6.28-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (799 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 799.9/799.9 kB 52.2 MB/s eta 0:00:00
Installing collected packages: regex, nltk
Successfully installed nltk-3.9.4 regex-2026.6.28

In [8]:
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /home/jovyan/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [9]:
#tokenization data
tokens=[word_tokenize(x) for x in cleaned_list]

In [10]:
len(tokens[0])

20

In [11]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [12]:
#contain all the stopwords of english lang
stop=set(stopwords.words('english'))

In [13]:
for i in tokens:
    for j in i:
        if j in stop:
            i.remove(j)

In [14]:
len(tokens[0])

17

In [15]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
stremmed_data=[]
for message in tokens:
    upms=[ps.stem(word) for word in message]
    stremmed_data.append(upms)

In [16]:
stremmed_data[0]

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'in',
 'bugi',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat']

In [17]:
from nltk import pos_tag
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/jovyan/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [18]:
pos_token=[pos_tag(message) for message in tokens]

In [19]:
pos_token[0]

[('go', 'VB'),
 ('jurong', 'JJ'),
 ('point', 'NN'),
 ('crazy', 'NN'),
 ('available', 'JJ'),
 ('in', 'IN'),
 ('bugis', 'NN'),
 ('n', 'RB'),
 ('great', 'JJ'),
 ('world', 'NN'),
 ('la', 'NN'),
 ('e', 'VBP'),
 ('buffet', 'JJ'),
 ('cine', 'NN'),
 ('got', 'VBD'),
 ('amore', 'RB'),
 ('wat', 'JJ')]

In [20]:
from nltk.corpus import wordnet
nltk.download('wordnet')
def get_wordner_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

[nltk_data] Downloading package wordnet to /home/jovyan/nltk_data...

In [21]:
get_wordner_pos('VB')

'v'

In [22]:
import nltk
from nltk.stem import WordNetLemmatizer

# Download required NLTK resources
nltk.download('wordnet')
nltk.download('omw-1.4')  # Recommended for extended wordnet support

# Initialize the lemmatizer
lm = WordNetLemmatizer()
lemma_data=[]
for message in pos_token:
    temp=[]
    for j in message:
        temp.append(lm.lemmatize(j[0],get_wordner_pos(j[1])))
    lemma_data.append(temp)

[nltk_data] Downloading package wordnet to /home/jovyan/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/jovyan/nltk_data...

In [23]:
lemma_data[0]

['go',
 'jurong',
 'point',
 'crazy',
 'available',
 'in',
 'bugis',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet',
 'cine',
 'get',
 'amore',
 'wat']

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [25]:
documnets=["".join(message) for message in lemma_data]
X=cv.fit_transform(documnets).toarray()

In [26]:
len(X)

5572

In [27]:
y=df['Category'].replace({'ham':1,'spam':0})

/tmp/ipykernel_21730/3544358524.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y=df['Category'].replace({'ham':1,'spam':0})

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()

In [30]:
lg.fit(X_train,y_train)

LogisticRegression()

In [31]:
lg.score(X_test,y_test)

0.8690582959641255